// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Zy8QRjthRtos8S10DnQTWZ87i_NkrQg',
    appId: '1:687380094234:web:7f1a7b386f59e5a077a0a3',
    messagingSenderId: '687380094234',
    projectId: 'chat-connect-86391',
    authDomain: 'chat-connect-86391.firebaseapp.com',
    storageBucket: 'chat-connect-86391.firebasestorage.app',
    measurementId: 'G-3KTW5TDD0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4Lg5NfG5fE5_augjKBeicNPW95esAl8',
    appId: '1:687380094234:android:fc05aec7eefec84077a0a3',
    messagingSenderId: '687380094234',
    projectId: 'chat-connect-86391',
    storageBucket: 'chat-connect-86391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk1LQt2lAd1WYqXxxyzwfj2c-e2JC_Lp0',
    appId: '1:687380094234:ios:93f09a7e11c14de577a0a3',
    messagingSenderId: '687380094234',
    projectId: 'chat-connect-86391',
    storageBucket: 'chat-connect-86391.firebasestorage.app',
    iosBundleId: 'com.vbanawalkar.chatconnect.chatconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk1LQt2lAd1WYqXxxyzwfj2c-e2JC_Lp0',
    appId: '1:687380094234:ios:93f09a7e11c14de577a0a3',
    messagingSenderId: '687380094234',
    projectId: 'chat-connect-86391',
    storageBucket: 'chat-connect-86391.firebasestorage.app',
    iosBundleId: 'com.vbanawalkar.chatconnect.chatconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Zy8QRjthRtos8S10DnQTWZ87i_NkrQg',
    appId: '1:687380094234:web:f11be958d2f839b377a0a3',
    messagingSenderId: '687380094234',
    projectId: 'chat-connect-86391',
    authDomain: 'chat-connect-86391.firebaseapp.com',
    storageBucket: 'chat-connect-86391.firebasestorage.app',
    measurementId: 'G-JB88PP4M8H',
  );
}
